/*
 * This file is generated by jOOQ.
 */
package ru.ver.jooq;


import ru.ver.jooq.tables.Test;
import ru.ver.jooq.tables.TestV;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.test</code>.
     */
    public static final Test TEST = Test.TEST;

    /**
     * The table <code>public.test_v</code>.
     */
    public static final TestV TEST_V = TestV.TEST_V;
}
